import React from 'react';//import library react
import Link from 'next/link';//import link from next.js
import axios from 'axios';
import Form from 'muicss/lib/react/form';//import from from muicss library
import Input from 'muicss/lib/react/input';//import input from muicss library
import Button from 'muicss/lib/react/button';//import button from muicss library
import TopBar from '../components/topBar';//import TopBary
export default class extends React.Component {//this default class will extends react component 

  constructor(props) {
    super(props);
    this.state = { VIEW: [], status: this.props.url.query.status }
    this.smsLogin = this.smsLogin.bind(this);
    this.emailLogin = this.emailLogin.bind(this);
  }
  componentDidMount() {
    let status = this.state.status;
    if (status === 'wrong') {
      window.alert('Invalid Username and Password');
    }
    axios.get('/view').then((response) => {
      this.setState({ VIEW: response.data });
      // initialize Account Kit with CSRF protection
      AccountKit.init(
        {
          appId: response.data.appId,
          state: response.data.csrf,
          version: response.data.version,
          fbAppEventsEnabled: true
        }
      );
    })
  }

  smsLogin() {
    AccountKit.login(
      'PHONE', {}, function loginCallback(response) {
        if (response.status === "PARTIALLY_AUTHENTICATED") {
          document.getElementById("code").value = response.code;//authorization code 
          document.getElementById("csrf").value = response.state;//csrf value generated by loginCallback
          document.getElementById("login_success").submit();
        }
        else if (response.status === "NOT_AUTHENTICATED") {
          // handle authentication failure
        }
        else if (response.status === "BAD_PARAMS") {
          // handle bad parameters
        }
      }
    )
  }

  emailLogin() {
    AccountKit.login(
      'EMAIL', {}, function loginCallback(response) {
        console.log(response);
        if (response.status === "PARTIALLY_AUTHENTICATED") {
          document.getElementById("code").value = response.code;
          document.getElementById("csrf").value = response.state;
          document.getElementById("login_success").submit();
        }
        else if (response.status === "NOT_AUTHENTICATED") {
          // handle authentication failure
        }
        else if (response.status === "BAD_PARAMS") {
          // handle bad parameters
        }
      }
    );
  }
  render() {//render() will render the elements in browser
    return (//return() will return those elements
      <main> {/*main content*/}
        <TopBar />
        <div id="loginUser">
          <Form method='post' action='/loginUser'>{/*post the form data to /loginUser*/}
            <Input id="email" type="text" name="username" hint="Username" required />
            <Input id="password" type="password" name="password" hint="Password" required />
            <Button variant="raised">Login</Button>
          </Form>
          <br />
          <Button type="button" data-toggle="modal" data-target="#exampleModal" color="primary">Login With Facebook</Button>
          <div className="modal fade" id="exampleModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div className="modal-dialog" role="document">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title" id="exampleModalLabel">Login With Facebook</h5>
                  <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div className="modal-body">
                  <Button onClick={this.smsLogin} color="primary">Login via SMS</Button>
                  <br />
                  <br />
                  <h3>OR</h3>
                  <br />
                  <Button onClick={this.emailLogin} color="danger">Login via Email</Button>
                  <form id="login_success" method="post" action="/login_success">
                    <input id="csrf" type="hidden" name="csrf" />
                    <input id="code" type="hidden" name="code" />
                  </form>
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <br />
          <br />
          <p id="signup">Click here to <Link href='/signup'><a>Signup</a></Link></p>
        </div>
      </main>
    )
  }
}
